# Generated by Django 4.0.2 on 2024-03-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.TextField(blank=True),
        ),
    ]
