# Generated by Django 4.0.2 on 2024-03-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_collection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='uuid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
